### ISSUE TITLE
[Feature] Run the project using GitHub workflows

### ISSUE THREAD

**Issue by T145** [montysecurity/C2-Tracker#1]
If you'd like to not have to worry about running this script on your own machine every day, likely have to manage port forwards, and expose yourself to greater security risk, you could run this task as a GitHub workflow! You can securely stash your Shodan API key and run the script using my own hardened VM: https://github.com/T145/black-mirror/pkgs/container/black-mirror

**Comment by montysecurity** [comment]
Thanks for the tip! I will look into this.
