### ISSUE TITLE
Add Bandit Stealer to Tracking

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#12]
Bandit Stealer has dropped off ~Dec 2023 but malware has a way of flaring back to life in unexpected ways.  I used the following attributes in Shodan to track it previously and it may still be a good addition.

http.title:"Login" 
http.html:"Welcome to Bandit"
"Content-Length: 4125" 
port:8080

It seems to call assets/js/vendor.min.js (MD5 hash:95d214607dde7d2d9dcd93ee03620901) and it can be used a supplementary check. I've also observed "Bandit Login" as a title, though only in much older cases.

**Comment by montysecurity** [comment]
Added this, thank you!
