### ISSUE TITLE
Add Pantegana RAT to tracking

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#14]
Pantegana RAT
https://github.com/cassanof/pantegana

http.html_hash:-1255326477 ssl:pantegana 

https://www.shodan.io/search?query=http.html_hash%3A-1255326477+ssl%3Apantegana+

This misses a few that have a Content length of 19 in the page but they are a minority.

**Comment by montysecurity** [comment]
Hey thanks for all of your contributions! I added this one but elected to focus strictly on the SSL certs. Pulled them from the make file of the project - https://github.com/cassanof/pantegana/blob/master/Makefile

        "Pantegana": [
            "ssl:Pantegana ssl:localhost",
            "ssl.cert.issuer.cn:'Pantegana Root CA'"
        ]
