### ISSUE TITLE
Add Viper to tracking

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#15]
Viper Malware
Shodan: http.html_hash:-1250764086
https://www.shodan.io/search?query=http.html_hash%3A-1250764086

We can use ETag value "33c95-45-4e400411" to add another parameter, if needed.

Correlate on Censys: https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=services.http.response.favicons.md5_hash%3D%22a7469955bff5e489d2270d9b389064e1%22

**Comment by montysecurity** [comment]
This has been added. Thank you for all of your support!
