### ISSUE TITLE
Villain

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#19]
I've been working on this one since I observed it used vs a client.

https://github.com/t3l3machus/Villain

More a request to find a way to detect it than a firm detection.

**Comment by montysecurity** [comment]
Working on this

**Comment by montysecurity** [comment]
Did some testing and got this added: https://github.com/montysecurity/C2-Tracker/commit/5f451687e135062cc2b4a0fa3317d87af281b9ac
