### ISSUE TITLE
Add UnamWebPanel to Tracking

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#21]
My apologies that these are coming out piece by piece. I'm verifying things more clearly for Shodan and only have a small amount of bandwidth.  Enjoying it, however.

html:"unam_lib.js" http.favicon.hash:-1278680098,-1531496738
https://github.com/UnamSanctam/UnamWebPanel

**Comment by montysecurity** [comment]
Added this plus a search for the html title, thanks

```
"UnamWebPanel": [
            "html:unam_lib.js http.favicon.hash:-1278680098,-1531496738",
            "http.title:'Unam Web Panel &mdash; Login'"
        ]
```
