### ISSUE TITLE
Add Gozi/Mekotio to tracking

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#22]
Censys matching here:

services.software.product: {Gozi, Mekotio}
https://search.censys.io/search?resource=hosts&q=services.software.product%3A+%7BGozi%2C+Mekotio%7D

**Comment by montysecurity** [comment]
Added these 2 seperately as 2 different searches

```
       "Mekotio Trojan": [
            "services.software.product=`Mekotio`"
        ],
        "Gozi Trojan": [
            "services.software.product=`Gozi`"
        ]
```
