### ISSUE TITLE
AcidRain

### ISSUE THREAD

**Issue by sws-lcocco** [montysecurity/C2-Tracker#3]
Hi, maybe `AcidRain` string in query is wrong?
(no IP is found for that product)

Thanks in advance,
L

**Comment by montysecurity** [comment]
Hey thanks for reporting. I found the issue. There was a bug where it would write an empty file if a search had no results. That has been fixed. It does not create the file for that tool if there are no results.

Again, thanks!
- monty

**Comment by sws-lcocco** [comment]
Hi,
thanks to you (AcidRain wasn't the only empty file)

But I think the query string for AcidRain is wrong (in the code I read the string `AcridRain`)

L

**Comment by montysecurity** [comment]
You are totally right! That has been wrong for some time now...thank you for pointing it out. It has been fixed.
