### ISSUE TITLE
Red Guard C2 Redirector

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#35]
https://hunt.io/blog/detecting-redguard-c2-redirector

"307 Temporary Redirect" port:80,443,8443 html:"https://360.net"
https://www.shodan.io/search?query=%22307+Temporary+Redirect%22+port%3A80%2C443%2C8443+html%3A%22https%3A%2F%2F360.net%22

**Comment by montysecurity** [comment]
Added this. Made some slight changes to the query as I came across some redirectors on different ports than listed. Thanks for contributing! Nice work

Commit: https://github.com/montysecurity/C2-Tracker/commit/ab5ff6e8d324c95b2ceda2a764fad518982d88fa
