### ISSUE TITLE
Oyster Backdoor

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#36]
https://www.rapid7.com/blog/post/2024/06/17/malvertising-campaign-leads-to-execution-of-oyster-backdoor/
https://thehackernews.com/2024/06/oyster-backdoor-spreading-via.html

http.html_hash:-51903740 port:80,443
https://www.shodan.io/search?query=http.html_hash%3A-51903740+port%3A80%2C443

**Comment by montysecurity** [comment]
Added this, thank you! https://github.com/montysecurity/C2-Tracker/commit/429407927b522946b62bfc6ba9040550a9486eae
