### ISSUE TITLE
SpiceRAT

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#37]
https://hunt.io/blog/the-secret-ingredient-unearthing-suspected-spicerat-infrastructure-via-html-response

http.html_hash:114440660
https://www.shodan.io/search?query=http.html_hash%3A114440660

This is the most stable response I can find for the SpiceRAT C2 in Shodan. It catches the HTTP/Port 80 C2 but doesn't cover the TLS versions. Those are harder to boil into one query, though I suspect its possible.

**Comment by montysecurity** [comment]
This one is interesting. I am seeing a sort of hash collision with the html_hash field. The supplied HTML hash matches the intended "<HTML>RESPONSE</HTML>" page

![image](https://github.com/user-attachments/assets/ecdaf5f9-3921-4120-9441-616d7635c2b3)

But it also appears to match a version of the pFSense login page.

![image](https://github.com/user-attachments/assets/12d2b656-52e7-4388-ba61-2f8a138dd826)

Now obviously the response headers are different.

SpiceRAT: 
![image](https://github.com/user-attachments/assets/3a2ebce6-7835-432c-82b8-f5208c281cb9)

pFSense:
![image](https://github.com/user-attachments/assets/ba7f2d7e-98a6-4d03-a394-3dcc75b08c73)


Given this I will add the response hash as an additional condition that must be met. So the search will be "http.headers_hash:1955818171 http.html_hash:114440660". I will added this and you should see the IPs in the next update cycle

Commit: https://github.com/montysecurity/C2-Tracker/commit/3c755c8bb29b173c6280dda7638bf51a72e4f349
