### ISSUE TITLE
Hunting Pupy/Dust RAT

### ISSUE THREAD

**Issue by salmanvss** [montysecurity/C2-Tracker#39]
Hi Team,

Came across 2 RAT's which are currently not being tracked here.
PupyRAT -
services.tls.certificates.leaf_data.subject.organizational_unit="CONTROL"
services.software.vendor="Pupy RAT"r="Pupy RAT"
services.software.uniform_resource_identifier="cpe:2.3:a:pupy-rat:pupy-rat:\*:\*:\*:\*:\*:\*:\*:\*"

Dust RAT - 
services.http.response.body:"Dust RAT v1.4.0"
services.http.response.html_tags="<title> Admin</title>" and services.software.vendor="Laravel" and services.port=18443

fofa 
"CommonName: www.dust.local"

Reference post - https://x.com/salmanvsf/status/1823587814015164567

My twitter username - https://x.com/salmanvsf
my gmail - salmanvs@gmail.com
linkedin - https://www.linkedin.com/in/salman-shaikh-666bb3b8/

**Comment by montysecurity** [comment]
Added these: https://github.com/montysecurity/C2-Tracker/commit/dcb62b86b695ed5cf9cfacf0ca815c5423ddbd13

Thanks for bringing them up
