### ISSUE TITLE
CobaltStrike False Positive Exclusion

### ISSUE THREAD

**Issue by Ricdotit** [montysecurity/C2-Tracker#4]
Hi,

I noticed a lot of potential false positive regarding the CobalStrike C2. 

The jarm fingerprinting: ssl.jarm:07d14d16d21d21d07c42d41d00041d24a458a375eef0c576d23a7bab9a9fb1+port:443  gives as an output thousand of IPs related to a big security vendor.  

You can se that almost all the IPs starting with 34.  or 35. are related to them.

I suggest to improve the code excluding that jarm fingerprinting if matches also the following query: ssl.cert.subject.cn:<vendor-domain>

Thanks in advance.

**Comment by Ricdotit** [comment]
errata corridge:

I suggest to improve the code excluding that jarm fingerprinting if matches also the following query: ssl.cert.subject.cn:example.com   (example should be of course substituted with  the security vendor domain)

**Comment by Ricdotit** [comment]
to help you, the domain that should be excluded is cybereason.net

**Comment by montysecurity** [comment]
Hey. Thank you for reporting. You're right, it seems like that fingerprint is no longer specific to CS. Instead of managing exclusions, I opted to remove that JARM from the list of signatures. The files in data/ have been updated.

Thanks for letting me know!
- monty
