### ISSUE TITLE
Tracking Bitrat using CN

### ISSUE THREAD

**Issue by Zizszs** [montysecurity/C2-Tracker#42]
Hi,

I found a new way to track bitrat. Currently script uses product name. However we could also use below CN .

CommonName: BitRAT
https://fofa.info/result?qbase64=Q29tbW9uTmFtZTogQml0UkFU
https://search.censys.io/search?q=services.tls.certificates.leaf_data.issuer.common_name%3D%22BitRAT%22&resource=hosts

Regards,
Salman Shaikh

**Comment by montysecurity** [comment]
Already tracking with product tag. Using the CN yields the same results. Skipping.
