### ISSUE TITLE
Add BlackNet to Tracking

### ISSUE THREAD

**Issue by corumir** [montysecurity/C2-Tracker#8]
Blacknet - https://github.com/suriya73/BlackNET
Shodan Search: https://www.shodan.io/search?query=http.title%3A%22BlackNet+-+Login%22

        "BlackNet C2": [
            "http.title:'BlackNet - Login'"
            ]

You can increase fidelity with http.favicon.hash:-1118063833 or http.favicon.hash:1571617949.

**Comment by montysecurity** [comment]
Added this and credited you in the README and source code. Thanks!
